//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolumeScanner2.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationTranslations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTranslations() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolumeScanner2.Resources.ApplicationTranslations", typeof(ApplicationTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New folder query ähnelt.
        /// </summary>
        public static string Button_NewQuery {
            get {
                return ResourceManager.GetString("Button_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show source code ähnelt.
        /// </summary>
        public static string Button_ViewSourceCode {
            get {
                return ResourceManager.GetString("Button_ViewSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New query ähnelt.
        /// </summary>
        public static string Dialog_NewQuery {
            get {
                return ResourceManager.GetString("Dialog_NewQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysis is running. ähnelt.
        /// </summary>
        public static string Message_AnalysisRunning {
            get {
                return ResourceManager.GetString("Message_AnalysisRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 4 / 4 - Calculating folder sizes. ähnelt.
        /// </summary>
        public static string Message_CalculatingFolderSizes {
            get {
                return ResourceManager.GetString("Message_CalculatingFolderSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1 / 4 - Collecting file information. ähnelt.
        /// </summary>
        public static string Message_CollectingFileInformation {
            get {
                return ResourceManager.GetString("Message_CollectingFileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3 / 4 Creating folder register. ähnelt.
        /// </summary>
        public static string Message_CreatingFolderRegister {
            get {
                return ResourceManager.GetString("Message_CreatingFolderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No path selected. ähnelt.
        /// </summary>
        public static string Message_NoPathSelected {
            get {
                return ResourceManager.GetString("Message_NoPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2 / 4 - Obtaining file sizes. ähnelt.
        /// </summary>
        public static string Message_QueryingFileSizes {
            get {
                return ResourceManager.GetString("Message_QueryingFileSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search aborted ähnelt.
        /// </summary>
        public static string Message_SearchAborted {
            get {
                return ResourceManager.GetString("Message_SearchAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Query: {0} ähnelt.
        /// </summary>
        public static string Text_Evaluation {
            get {
                return ResourceManager.GetString("Text_Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating cache ähnelt.
        /// </summary>
        public static string Title_AnalysisCacheIsBeingBuilt {
            get {
                return ResourceManager.GetString("Title_AnalysisCacheIsBeingBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Querying path information ähnelt.
        /// </summary>
        public static string Title_QueryingPath {
            get {
                return ResourceManager.GetString("Title_QueryingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string Token_File {
            get {
                return ResourceManager.GetString("Token_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        public static string Token_Folder {
            get {
                return ResourceManager.GetString("Token_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in explorer ähnelt.
        /// </summary>
        public static string Tree_OpenInExplorer {
            get {
                return ResourceManager.GetString("Tree_OpenInExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collapse recursive ähnelt.
        /// </summary>
        public static string Tree_RecursiveCollapse {
            get {
                return ResourceManager.GetString("Tree_RecursiveCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expand recursive ähnelt.
        /// </summary>
        public static string Tree_RecursiveExpand {
            get {
                return ResourceManager.GetString("Tree_RecursiveExpand", resourceCulture);
            }
        }
    }
}
